name: Cypress e2e

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    container: cypress/browsers:node12.13.0-chrome80-ff74
    strategy:
      matrix:
        node: [12]
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: node -v

      - name: Checkout
        uses: actions/checkout@2.3.0
 
      - name: Cypress run
        uses: cypress-io/github-action@v2.3.10
        with:
      #     start: npm run e2e
      #     # wait-on: http://localhsot:4200/
      #     # working-directory: apps/consultatio-e2e
          record: true
          browser: chrome
          headless: true
      #     # config-file: apps/consultatio-e2e/cypress.json
      #   env:
      #     CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}