name: Cypress e2e

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        node: [10, 12]
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: node -v

      - name: Checkout
        uses: actions/checkout@v1
        # with:
        #   repository: https://github.com/ksakae1216/tribulatio

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          record: true
          browser: chrome
          headless: "true"
        # env:
        #   CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}